#  maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

clone:
    depth: full    # SonarCloud scanner needs the full history to assign issues properly

definitions:
    caches:
        sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
    steps:
        - step: &build-test
            name: Build and Test
            caches:
               - maven
            script:
                - mvn -B verify --file pom.xml
            artifacts:
                - target/** 
            after-script:
                # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
                - pipe: atlassian/checkstyle-report:0.2.0
        - step: &build-test-sonarcloud
            name: Build, Test & Analyze on SonarCloud
            caches:
                - maven
                - sonar
            script:
                - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml
            artifacts:
                - target/** 
            after-script:
              - if [ $BITBUCKET_EXIT_CODE -eq 0 ]; then exit $BITBUCKET_EXIT_CODE; fi
              - pipe: atlassian/opsgenie-send-alert:0.5.3
                variables:
                  GENIE_KEY: $OPSGENIE_KEY
                  MESSAGE: '单元测试或静态代码扫描失败'
                  PRIORITY: 'P1'
                  SOURCE: 'Bitbucket Pipelines'
        - step: &build-test-securityscan
            name: Security Scan
            script:
                # Run a security scan for sensitive data.
                # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
                - pipe: atlassian/git-secrets-scan:0.4.3
        - step: &deploy-to-staging-environment
            name: 'Deployment to Staging Environment'
            deployment: staging
            trigger: 'manual'
            script:
                - echo "Your deployment to production script goes here..."
        - step: &deploy-to-production-environment
            name: 'Deployment to Production Environment on Alibaba Cloud'
            deployment: production
            script:
                - pipe: atlassian/scp-deploy:0.3.3
                  variables:
                        USER: $USER
                        SERVER: $SERVER
                        REMOTE_PATH: '/home/dxy/yyzone/'
                        LOCAL_PATH: 'target/*'
                # Restart the Service on Alibaba Cloud...'
                - ssh $USER@$SERVER "cd /home/dxy/yyzone/deploy && ./deploy.sh ../bmicalculator-0.0.1-SNAPSHOT.jar"
pipelines:
    default:
        - step: *build-test
    branches:
        master:
            - step: *build-test-sonarcloud
            - step: *build-test-securityscan
            - step: *deploy-to-staging-environment
            # - step: *deploy-to-production-environment
    pull-requests:
        '**':
            - step: *build-test-sonarcloud
            - step: *build-test-securityscan