#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
    
pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
            - sonar
          script:
            # - pipe: sonarsource/sonarcloud-scan:1.2.2
            # variables:
            #   SONAR_TOKEN: '<string>'  # Optional
            #   EXTRA_ARGS: '<string>'  # Optional
            #   SONAR_SCANNER_OPTS: '<string>'  # Optional
            #   DEBUG: '<boolean>'  # Optional
            - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml
          artifacts:
            - target/**
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.2.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.4.3