#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

clone:
    depth: full    # SonarCloud scanner needs the full history to assign issues properly

definitions:
    caches:
        sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
    steps:
        - step: &build-test-sonarcloud
            name: Build, test and analyze on SonarCloud
            caches:
                - maven
                - sonar
            script:
                - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml
            artifacts:
                - target/** 
        - step: &build-test
            name: Build and Test
            caches:
               - maven
            script:
                - mvn -B verify --file pom.xml
            artifacts:
                - target/** 
            after-script:
                # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
                - pipe: atlassian/checkstyle-report:0.2.0
        - step: &build-test-securityscan
            name: Security Scan
            script:
                # Run a security scan for sensitive data.
                # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
                - pipe: atlassian/git-secrets-scan:0.4.3
        - step: &deploy-to-staging-environment
            name: 'Deployment to Staging'
            deployment: staging
            script:
                - echo "Your deployment to staging script goes here..."
        - step: &deploy-to-production-environment
            name: 'Deployment to Production'
            deployment: production
            trigger: 'manual'
            script:
                - echo "Your deployment to production script goes here..."
pipelines:
    default:
        -step: *build-test
    deplyment:
        -step: *deploy-to-staging-environment
        
    branches:
        master:
            - step: *build-test-sonarcloud
            - step: *build-test-securityscan
    pull-requests:
        '**':
            - step: *build-test-sonarcloud
            - step: *build-test-securityscan